LOG_LEVEL: "DEBUG"
LOG_FORMAT: "json"
SERVER_PORT: 8080
SERVER_READ_TIMEOUT: 20
SERVER_WRITE_TIMEOUT: 15
SERVER_IDLE_TIMEOUT: 20
DB_NAME: "covid"
DB_HOST: "localhost"
DB_USER: "postgres"
DB_PASSWORD: ""
DB_PORT: 5432
DB_MAX_POOL_SIZE: 5
